# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site/SEO settings
email: magtrix333@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/

title: MAG.WORLD 
description: A window into my mind
github_username: magtrix11

# Email and twitter are optional:
email: magtrix333@gmail.com  
twitter_username: magtrix_nft

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Build settings
markdown: kramdown
remote_theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag

minima:
  skin: solarized-dark
  
header_pages:
  - about.md
  - portfolio.md
  - this_could_be_interesting.md
  - what_do_i_know.md
  
